baseURL = ""
languageCode = "en-us"
relativeURLs = true
theme = "hildemorin"
paginate = 5.0
summaryLength = 50

[taxonomies]
tag = "tags"

[params]
copyright = "Content copyright Â© 2006-2018 Hilde Morin"
updated = "February 2018"
